### ISSUE TITLE
NoneType object is not iterable

### ISSUE THREAD

**Issue by 88plug** [vertcoin/p2pool-vtc#18]
Running standard vertcoin pool configs -

Error in DeferredResource handler:
Traceback (most recent call last):
  File "/p2pool-vtc/p2pool/util/deferred_resource.py", line 24, in render
    defer.maybeDeferred(resource.Resource.render, self, request).addCallbacks(finish, finish_error)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/p2pool-vtc/p2pool/web.py", line 198, in render_GET
    res = yield self.func(*self.args)
  File "/p2pool-vtc/p2pool/web.py", line 342, in <lambda>
    new_root.putChild('share', WebInterface(lambda share_hash_str: get_share(share_hash_str)))
  File "/p2pool-vtc/p2pool/web.py", line 331, in get_share
    other_transaction_hashes=['%064x' % x for x in share.get_other_tx_hashes(node.tracker)],
exceptions.TypeError: 'NoneType' object is not iterable

**Comment by metalicjames** [comment]
This is normal. It happens when the web UI tries to get information for a share that the pool hasn't downloaded yet. It can be safely ignored.
