### ISSUE TITLE
v0.2.0rc1

### ISSUE THREAD

**Issue by Tanariel** [vertcoin/p2pool-vtc#8]
Running the v0.2.0rc1 with the new wallet and getting this error on network 2 : 

```
2017-12-03 23:01:15.205185  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
Error in DeferredResource handler:
Traceback (most recent call last):
  File "/home/jb/p2pool-vtc/p2pool/util/deferred_resource.py", line 24, in render
    defer.maybeDeferred(resource.Resource.render, self, request).addCallbacks(finish, finish_error)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 198, in render_GET
    res = yield self.func(*self.args)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 203, in <lambda>
    web_root.putChild('rate', WebInterface(lambda: p2pool_data.get_pool_attempts_per_second(node.tracker, node.best_share_var.value, decent_height())/(1-p2pool_data.get_average_stale_prop(node.tracker, node.best_share_var.value, decent_height()))))
  File "/home/jb/p2pool-vtc/p2pool/data.py", line 630, in get_pool_attempts_per_second
    assert dist >= 2
exceptions.AssertionError:
```

This happens on network 2 when trying to load the web-ui on browser.
You can see it on http://aupool.grasdouble.com:9181/static/ (or 9171)

Any idea ? :)

**Comment by metalicjames** [comment]
Can you try rc2?

I don't know about the UI you use but for the default one it works fine.

**Comment by Tanariel** [comment]
Ok, so when i checked the server this morning the wallet had crashed 30 mins after i launched it.
I restarted everything without to change anything and all started to run ok.

So at the moment i'm running the rc1 + the 0.12 wallet and all is ok.
I just updated to rc2 and all is ok too.

Just as reference the ui i'm using is this one : https://github.com/Cremator/p2pool-ui.git

Thanks again for the help. :)

**Comment by Tanariel** [comment]
Unfortunately this is back.

I installed a new pool with the 0.12 wallet and the v0.2.0 vertion of the pool and all the network 2 nodes are doing this error.

```
Error in DeferredResource handler:
Traceback (most recent call last):
  File "/home/jb/p2pool-vtc/p2pool/util/deferred_resource.py", line 24, in render
    defer.maybeDeferred(resource.Resource.render, self, request).addCallbacks(finish, finish_error)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 198, in render_GET
    res = yield self.func(*self.args)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 203, in <lambda>
    web_root.putChild('rate', WebInterface(lambda: p2pool_data.get_pool_attempts_per_second(node.tracker, node.best_share_var.value, decent_height())/(1-p2pool_data.get_average_stale_prop(node.tracker, node.best_share_var.value, decent_height()))))
  File "/home/jb/p2pool-vtc/p2pool/data.py", line 630, in get_pool_attempts_per_second
    assert dist >= 2
exceptions.AssertionError:
```


I tried to restart the wallet, the network 2 pools but there is no way i can't make it work :(

This is very strange as the last time it somehow fixed by itself and the network 1 is running without a single problem.

http://54.37.220.201:9181/static/
http://54.37.220.202:9181/static/
http://54.37.220.203:9181/static/

**Comment by Tanariel** [comment]
Getting this error in the browser :

<img width="990" alt="screenshot_63" src="https://user-images.githubusercontent.com/1983686/33856526-1ad4d60a-ded1-11e7-972d-5054cdbaa136.png">

**Comment by Tanariel** [comment]
trying to revert to default ui i get this : 

```
Error in DeferredResource handler:
Traceback (most recent call last):
  File "/home/jb/p2pool-vtc/p2pool/util/deferred_resource.py", line 24, in render
    defer.maybeDeferred(resource.Resource.render, self, request).addCallbacks(finish, finish_error)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 198, in render_GET
    res = yield self.func(*self.args)
  File "/home/jb/p2pool-vtc/p2pool/web.py", line 347, in <lambda>
    new_root.putChild('best_share_hash', WebInterface(lambda: '%064x' % node.best_share_var.value))
exceptions.TypeError: %x format: a number is required, not NoneType
```


<img width="991" alt="screenshot_64" src="https://user-images.githubusercontent.com/1983686/33857022-b6dc5194-ded2-11e7-8946-90f65ff58950.png">

**Comment by Tanariel** [comment]
Again the problem seems to have resolved by itself. It seems that when initialising a new pool there is a slight delay where the system is missing some data or not initialising them. But few hours after, all seems to settle and work normally. I don't know if this can be seen as a bug or just a disturbance in the network :)

**Comment by Tanariel** [comment]
Yeah sorry.
